name: Build V.L.A.D. APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Ferramentas de Compilação do Android
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake autopoint gettext patch

      - name: Instalar Buildozer e Cython Estável
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" virtualenv buildozer

      - name: Compilar APK com o Buildozer
        run: |
          yes | buildozer android debug

      - name: Guardar o APK Pronto (Upload)
        uses: actions/upload-artifact@v4
        with:
          name: VLAD-AI-APK
          path: bin/*.apk
